"""Source importers for course schedules and curriculum plans."""

from .catalog_merge import (
    MergedCatalog,
    MergedCourse,
    MergeDisposition,
    MergedTeachingClass,
    MergeStatistics,
    merge_snapshots,
)
from .cug_xls import (
    OLE2_SIGNATURE,
    WeekExpression,
    WorkbookImportError,
    import_schedule_files,
    import_schedule_zip,
    parse_schedule_matrix,
    parse_week_expression,
    parse_workbook_bytes,
    parse_workbook_file,
)
from .models import (
    CatalogSnapshot,
    CellReference,
    Confidence,
    ImportedCourseSchedule,
    ImportedMeeting,
    ImportedTeachingClass,
    ImportIssue,
    IssueSeverity,
    SourceDocument,
    TimePrecision,
)
from .safe_zip import (
    SafeZipEntry,
    UnsafeArchiveError,
    ZipSafetyLimits,
    decode_legacy_zip_name,
    read_safe_zip_entries,
    safe_windows_filename,
    validate_member_path,
)

__all__ = [
    "OLE2_SIGNATURE",
    "CatalogSnapshot",
    "CellReference",
    "Confidence",
    "ImportIssue",
    "ImportedCourseSchedule",
    "ImportedMeeting",
    "ImportedTeachingClass",
    "IssueSeverity",
    "MergeDisposition",
    "MergeStatistics",
    "MergedCatalog",
    "MergedCourse",
    "MergedTeachingClass",
    "SafeZipEntry",
    "SourceDocument",
    "TimePrecision",
    "UnsafeArchiveError",
    "WeekExpression",
    "WorkbookImportError",
    "ZipSafetyLimits",
    "decode_legacy_zip_name",
    "import_schedule_files",
    "import_schedule_zip",
    "merge_snapshots",
    "parse_schedule_matrix",
    "parse_week_expression",
    "parse_workbook_bytes",
    "parse_workbook_file",
    "read_safe_zip_entries",
    "safe_windows_filename",
    "validate_member_path",
]
