const {chromium}=require('playwright');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true, channel:'msedge'});
 const page=await browser.newPage({viewport:{width:1360,height:1000}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8876');
 const token=await page.evaluate(async()=>{const r=await fetch('/api/auth/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:'browser_'+Date.now(),password:'browser-test-1234'})});return (await r.json()).access_token;});
 await page.evaluate(t=>localStorage.setItem('cugPlannerToken',t),token);
 await page.reload();
 await page.locator('#profile-college').fill('工程学院');await page.locator('#profile-major').fill('土木工程');await page.locator('#profile-cohort').selectOption('2024');
 await page.locator('#profile-form button[type=submit]').click();
 await page.waitForFunction(()=>document.querySelector('#profile-status').textContent==='已保存');
 await page.waitForTimeout(400);
 assert.equal(await page.locator('.add-methods .method-card').count(),3);
 await page.locator('#open-manual-editor').click();
 await page.locator('#custom-name').fill('浏览器测试课');
 await page.locator('[data-weeks]').fill('1-5,7-8');await page.locator('[data-weekday]').selectOption('2');
 await page.locator('[data-start]').fill('5');await page.locator('[data-end]').fill('6');
 await page.locator('#course-editor-form button[type=submit]').click();
 await page.waitForFunction(()=>!document.querySelector('#course-editor').open);
 await page.locator('#generate-plan').click();
 await page.waitForFunction(()=>document.querySelector('#plan-results').textContent.includes('浏览器测试课'));
 await page.locator('[data-view-week]').selectOption('6');
 assert.equal(await page.locator('.timetable .class-block').count(),0);
 await page.locator('[data-view-week]').selectOption('1');
 await page.screenshot({path:'tmp/browser-desktop.png',fullPage:true});
 await page.reload();
 await page.waitForFunction(()=>document.querySelector('#selected-courses').textContent.includes('浏览器测试课'));
 await page.locator('[data-edit-course]').click();
 assert.equal(await page.locator('[data-weeks]').inputValue(),'1,2,3,4,5,7,8');
 await page.locator('#custom-name').fill('修改后的课');await page.locator('[data-start]').fill('7');await page.locator('[data-end]').fill('8');
 await page.locator('#course-editor-form button[type=submit]').click();
 await page.waitForFunction(()=>document.querySelector('#selected-courses').textContent.includes('修改后的课'));
 await page.setViewportSize({width:390,height:844});
 await page.locator('[data-edit-course]').click();await page.screenshot({path:'tmp/browser-mobile.png',fullPage:false});
 await page.locator('#close-course-editor').click();
 await page.locator('#catalog-management summary').click();
 await page.locator('#restore-builtin-catalog').click();
 await page.waitForFunction(()=>document.querySelector('#catalog-import-status').textContent.includes('1212'));
 await page.locator('#course-search').fill('测试技术');
 await page.locator('#course-search-button').click();
 await page.waitForFunction(()=>document.querySelector('#course-search-results').textContent.includes('20739000'));
 await page.locator('#course-step').scrollIntoViewIfNeeded();
 await page.screenshot({path:'tmp/browser-mobile-courses.png',fullPage:false});
 await page.setViewportSize({width:1440,height:1000});
 await page.locator('#course-step').scrollIntoViewIfNeeded();
 await page.screenshot({path:'tmp/browser-desktop-courses.png',fullPage:false});
 await page.evaluate(()=>{const y=document.querySelector('#course-step').getBoundingClientRect().top+window.scrollY;window.scrollTo({top:y-85,behavior:'instant'});document.querySelector('#toast').className='toast';});
 await page.screenshot({path:'tmp/ui-course-page.png',fullPage:false});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
 assert.deepEqual(errors,[]);
 await browser.close();console.log('Browser create, solve, restore, edit, mobile: PASS');
})().catch(e=>{console.error(e);process.exit(1)});
